### ISSUE TITLE
Let me give you money for no benefit

### ISSUE THREAD

**Issue by n-rook** [nmlgc/rec98.nmlgc.net#1]
I am interested in supporting the rec98 project in appreciation for all of the work you have done already. However, whenever I check the crowdfunding page, you are always sold out. I understand that the crowdfunding page exists to fund new work and make sure people don't have too high expectations of you. But have you considered adding an additional way to give money as appreciation for work that has already been done?

**Comment by nmlgc** [comment]
The fact that I'm permanently sold out hasn't escaped me, that's why I increased prices last month. 🙂 The TH01 Sariel fight should be out by the end of next week, which consists of at least 7 pushes, leaving at least €210 worth of work available in the store afterwards.
But yeah, if you *really* want nothing in return, I guess I'm fine with accepting donations. Leaving this dead-end RL job sooner rather than later would be pretty great, after all!

[Here you go.](https://rec98.nmlgc.net/donate)
