### ISSUE TITLE
The link to the "Position Independence" section of the FAQ doesn't automatically scroll to "Position Independence"

### ISSUE THREAD

**Issue by 32th-System** [nmlgc/rec98.nmlgc.net#5]
Links that go "https://rec98.nmlgc.net/faq#something" don't automatically scroll to "something". For example, the link to the ["Position Independence"](https://rec98.nmlgc.net/faq#position-independence) section of the FAQ doesn't automatically scroll to "Position Independence"

**Comment by nmlgc** [comment]
That's because the label is actually named [`pi-what`](https://rec98.nmlgc.net/faq#pi-what), to distinguish it from [`pi-how`](https://rec98.nmlgc.net/faq#pi-how). You were probably referring to [this one in the main repo](https://github.com/nmlgc/ReC98/commit/a0f50a92ce877167d3eca6cca8f5c3a49577d34a), which I just fixed. There's also one in this repo, which I'm going to fix tomorrow together with a whole other bunch of typos. Thanks for pointing it out!
